### ISSUE TITLE
Problem with partial string match

### ISSUE THREAD

**Issue by sickel** [grafana/grafana-json-datasource#288]
I am reading in statusjson data from nagios. 

A part of it:
[nagiosexample.txt](https://github.com/marcusolsson/grafana-json-datasource/files/9052848/nagiosexample.txt)

I want to do a partial match on $.data.hostlist.[*].name, so I do

$.data.hostlist[?(@.name=~/bb/)].name

I would expect to get back [aaknes-bb]. What I do get is [-1, -1]. And indeed, if I do

$.data.hostlist[?(@.name=~/bb/)]. I get 

{"name":-1,"plugin_output":"OK - x.y.z.z1: rta 726.213ms, (...)
{"name":-1,"plugin_output":"OK - x.y.z.z2: rta 710.566ms, (...)

and so on, rather than filtering, I have rewritten the json.

**Comment by sickel** [comment]
This may be the same issue as https://github.com/marcusolsson/grafana-json-datasource/issues/185

**Comment by gabor** [comment]
hi @sickel , filte rexpressionss are not supported in the plugin anymore,  since version `1.3.5`, for security reasons (see https://grafana.com/grafana/plugins/marcusolsson-json-datasource/?tab=changelog for more details).

in the https://grafana.com/docs/plugins/marcusolsson-json-datasource/latest/jsonpath/#filters section several possible workarounds are described. i hope this helps.
